services:
  app:
    container_name: "ai-integration"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"  # Exposing port 3000 to host
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/requests_db
    command: npx nodemon server.js
    depends_on:
      - mongo
    networks:
      - shared_network  # Using shared network for communication

  mongo:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - shared_network  # Ensuring Mongo is also in shared network

volumes:
  mongo_data:

networks:
  shared_network:
    external: true  # Using external shared network